version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: orders_raw
      - name: customers_raw
      - name: order_items_raw
      - name: payments_raw
      - name: reviews_raw
      - name: products_raw
      - name: sellers_raw