name: 'olist_dbt'
version: '1.0.0'
config-version: 2

profile: 'olist_clickhouse'

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  olist_dbt:
    staging:
      +materialized: view
    core:
      +materialized: view
    marts:
      +materialized: table